# @see https://gitlab.com/explore/catalog/to-be-continuous/make

include:
  - component: $CI_SERVER_FQDN/to-be-continuous/make/gitlab-ci-make@1.5.0
    inputs:
      image: 'ubuntu:latest'

variables:
  MAKE_BUILD_ARGS: build

.make-base:
  cache:
    paths:
      - AmbientImpactItemFilter/.venv/

make-build:
  artifacts:
    paths:
      - AmbientImpactItemFilter/sounds/
      - Ambient.Impact.filter
      - license.md
      - readme.md
