# @see https://gitlab.com/explore/catalog/to-be-continuous/make

include:
  - component: $CI_SERVER_FQDN/to-be-continuous/make/gitlab-ci-make@1.5.0
    inputs:
      # Don't use the slim image because that doesn't have make.
      image: 'python:3'

variables:
  MAKE_BUILD_ARGS: build filter-dir=$ITEM_FILTER_DIR outfile=$OUTFILE
  ITEM_FILTER_DIR: AmbientImpactItemFilter
  OUTFILE: Ambient.Impact.filter

.make-base:
  cache:
    paths:
      - $ITEM_FILTER_DIR/.venv/
  artifacts:
    paths:
      - $ITEM_FILTER_DIR/sounds/
      - $OUTFILE
      - license.md
      - readme.md

make-build:
  rules:
    # Disable the default component job in favour of our 'build' job.
    - when: never

build:
  extends: .make-base
  stage: build
  # Disable cache so that we can test the virtual environment creation and
  # installation of Jinja.
  cache: []
  before_script:
    - !reference [.make-base, before_script]
    - apt-get -qq update
    - apt-get install -y jq
  script:
    - make ${TRACE+-d} $MAKE_BUILD_ARGS
  rules:
    - if:
      changes:
        - $ITEM_FILTER_DIR/**/*.j2
        - $ITEM_FILTER_DIR/**/*.json
        - .gitlab-ci.yml
        - makefile
