# @see https://gitlab.com/explore/catalog/to-be-continuous/make

include:
  - component: $CI_SERVER_FQDN/to-be-continuous/make/gitlab-ci-make@1.5.0
    inputs:
      # Don't use the slim image because that doesn't have make.
      image: 'python:3'

variables:
  MAKE_BUILD_ARGS: build

.make-base:
  cache:
    paths:
      - AmbientImpactItemFilter/.venv/
  artifacts:
    paths:
      - AmbientImpactItemFilter/sounds/
      - Ambient.Impact.filter
      - license.md
      - readme.md

make-build:
  rules:
    # Disable the default component job in favour of our 'build' job.
    - when: never

build:
  extends: .make-base
  stage: build
  # Disable cache so that we can test the virtual environment creation and
  # installation of Jinja.
  cache: []
  script:
    - make ${TRACE+-d} $MAKE_BUILD_ARGS
  rules:
    - if:
      changes:
        - AmbientImpactItemFilter/sounds/**.json
        - AmbientImpactItemFilter/templates/**.j2
        - .gitlab-ci.yml
        - makefile
