# @see https://gitlab.com/explore/catalog/to-be-continuous/make

include:
  - component: $CI_SERVER_FQDN/to-be-continuous/make/gitlab-ci-make@1.5.0
    inputs:
      # Don't use the slim image because that doesn't have make.
      image: 'python:3'

variables:
  MAKE_BUILD_ARGS: build filter-dir=$ITEM_FILTER_DIR outfile=$OUTFILE
  ITEM_FILTER_DIR: AmbientImpactItemFilter
  OUTFILE: Ambient.Impact.filter

.make-base:
  cache:
    paths:
      - $ITEM_FILTER_DIR/.venv/
  artifacts:
    paths:
      - $ITEM_FILTER_DIR/sounds/
      - $OUTFILE
      - license.md
      - readme.md

make-build:
  rules:
    # Disable the default component job in favour of our 'build' job.
    - when: never

build:
  extends: .make-base
  stage: build
  # Disable cache so that we can test the virtual environment creation and
  # installation of Jinja.
  cache: []
  before_script:
    # This allows extending the before_script from .make-base.
    - !reference [.make-base, before_script]
    - apt-get -qq update
    - apt-get install -y jq
  script:
    - make ${TRACE+-d} $MAKE_BUILD_ARGS
  rules:
    - if:
      changes:
        - $ITEM_FILTER_DIR/**/*.j2
        - $ITEM_FILTER_DIR/**/*.json
        - .gitlab-ci.yml
        - makefile
  artifacts:
    name: item-filter-dev

release:
  stage: package-build
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    # Run this when a tag is created.
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating $CI_COMMIT_TAG release."
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
