# @see https://gitlab.com/explore/catalog/to-be-continuous/make

include:
  - project: 'to-be-continuous/make'
    ref: '1.5.0'
    file: '/templates/gitlab-ci-make.yml'

variables:
  MAKE_BUILD_ARGS: build

.make-base:
  cache:
    paths:
      - AmbientImpactItemFilter/.venv/

make-build:
  artifacts:
    paths:
      - AmbientImpactItemFilter/sounds/
      - Ambient.Impact.filter
      - license.md
      - readme.md
